service: dotnet-serverless
frameworkVersion: '>=1.6.0 <2.1.0'
provider:
  name: aws
  runtime: dotnetcore2.1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - xray:GetSamplingRules
        - xray:GetSamplingTargets
        - xray:GetSamplingStatisticSummaries
      Resource: '*'
package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip